const fanStyles=document.createElement('link');fanStyles.rel='stylesheet';fanStyles.href='fan.css';document.head.append(fanStyles);const menu=document.querySelector('#menu'),nav=document.querySelector('nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});const stagePhotos={'T-Mobile':'stage-t-mobile.jpg',"Tito's":'stage-titos.jpg','Miller Lite':'stage-miller-lite.jpg','Lady Bird':'stage-lady-bird.jpg','BMI':'stage-bmi.jpg','Austin Kiddie Limits':'stage-austin-kiddie-limits.jpg','BeatBox':'stage-beatbox.jpg','Bonus Tracks':'stage-bonus-tracks.jpg'};document.querySelectorAll('.stage-grid article').forEach(card=>{const name=card.querySelector('h3')?.textContent,file=stagePhotos[name];if(!file)return;const old=card.querySelector('.stage-photo'),link=document.createElement('a');link.className='stage-photo has';link.href=`images/acl/${file}`;link.target='_blank';link.innerHTML=`<img src="images/acl/${file}" alt="${name} stage at ACL Festival" loading="lazy">`;old?.replaceWith(link)});
const notes={
2002:["Ryan Adams, Emmylou Harris, Wilco, Los Lobos, Patty Griffin","Nickel Creek, Robert Randolph & the Family Band, G. Love & Special Sauce, Asleep at the Wheel"],
2003:["R.E.M., Ben Harper, Sheryl Crow, Dwight Yoakam, Ryan Adams, Rosanne Cash","Kings of Leon, Bright Eyes, Drive-By Truckers, The Polyphonic Spree, Café Tacvba"],
2004:["Sheryl Crow, The Pixies, Trey Anastasio, Ben Harper, Elvis Costello, Modest Mouse","The Killers, Franz Ferdinand, My Morning Jacket, Calexico, Broken Social Scene"],
2005:["Coldplay, Oasis, The Black Crowes, The Allman Brothers Band, Widespread Panic, Wilco","Arcade Fire, The Black Keys, The Decemberists, Death Cab for Cutie, Bloc Party"],
2006:["Tom Petty & the Heartbreakers, Van Morrison, Willie Nelson, Massive Attack, The Flaming Lips","Kings of Leon, Gnarls Barkley, Cat Power, Iron & Wine, The Black Angels"],
2007:["Bob Dylan, Björk, The Killers, Muse, Arcade Fire, Wilco","Arctic Monkeys, LCD Soundsystem, The National, Regina Spektor"],
2008:["Foo Fighters, Robert Plant & Alison Krauss, Beck, David Byrne, Erykah Badu","The Black Keys, Vampire Weekend, Fleet Foxes, MGMT, Tegan and Sara"],
2009:["Pearl Jam, Dave Matthews Band, Kings of Leon, John Legend","Phoenix, Bon Iver, The Avett Brothers, Dr. Dog"],
2010:["The Eagles, Muse, Phish, The Strokes, M.I.A., The Flaming Lips","The xx, deadmau5, Vampire Weekend, Edward Sharpe & the Magnetic Zeros"],
2011:["Coldplay, Stevie Wonder, Kanye West, Arcade Fire, My Morning Jacket","Skrillex, Brandi Carlile, Gary Clark Jr., Fitz and the Tantrums"],
2012:["Red Hot Chili Peppers, Neil Young & Crazy Horse, The Black Keys, Jack White, Avicii","Childish Gambino, Alabama Shakes, The Lumineers, Michael Kiwanuka"],
2013:["Depeche Mode, The Cure, Muse, Kings of Leon, Lionel Richie, Phoenix","Kendrick Lamar, Tame Impala, Kacey Musgraves, HAIM, Grimes"],
2014:["Eminem, Pearl Jam, Outkast, Skrillex, Beck, Calvin Harris, Lana Del Rey","Sam Smith, Hozier, St. Vincent, Phantogram, CHVRCHES"],
2015:["Foo Fighters, Drake, Florence + the Machine, The Weeknd, Disclosure","Chance the Rapper, Halsey, Leon Bridges, Glass Animals"],
2016:["Radiohead, Mumford & Sons, Kendrick Lamar, LCD Soundsystem, Willie Nelson","Anderson .Paak, Lizzo, Flume, Maren Morris, Lucy Dacus"],
2017:["Jay-Z, Red Hot Chili Peppers, Chance the Rapper, The Killers, Gorillaz","Dua Lipa, MUNA, Portugal. The Man, Vance Joy, Royal Blood"],
2018:["Paul McCartney, Metallica, Childish Gambino, Arctic Monkeys, Travis Scott","Billie Eilish, Greta Van Fleet, Janelle Monáe, Khalid"],
2019:["Guns N’ Roses, Tame Impala, The Cure, Billie Eilish, Cardi B","Lizzo, Rosalía, Kacey Musgraves, Maggie Rogers"],
2021:["George Strait, Billie Eilish, Stevie Nicks, Miley Cyrus, RÜFÜS DU SOL","Megan Thee Stallion, Phoebe Bridgers, Finneas, girl in red"],
2022:["Red Hot Chili Peppers, P!nk, The Chicks, SZA, Kacey Musgraves","Japanese Breakfast, Wet Leg, Omar Apollo, Noah Cyrus"],
2023:["Kendrick Lamar, Foo Fighters, Mumford & Sons, ODESZA, Shania Twain, Niall Horan","Noah Kahan, The 1975, Maggie Rogers, Labrinth"],
2024:["Dua Lipa, Tyler, the Creator, Chris Stapleton, blink-182, Sturgill Simpson","Chappell Roan, Teddy Swims, Benson Boone, Reneé Rapp, Carin León"],
2025:["Hozier, Sabrina Carpenter, The Strokes, Doechii, The Killers, John Summit","Olivia Dean, ROLE MODEL, Mk.gee, Lola Young, Rilo Kiley"],
2026:["Charli xcx, Skrillex, Kings of Leon, Turnstile, RÜFÜS DU SOL, Lorde","Geese, Lola Young, CMAT, Audrey Hobert, Blood Orange, Sienna Spiro"]};
const years=Array.from({length:25},(_,i)=>2002+i),track=document.querySelector('#posterTrack'),caption=document.querySelector('#posterCaption'),details=document.querySelector('#lineupDetails');let selected=years.length-1;
function asset(y){if(y===2020)return null;const ext=y===2007?'gif':y===2024?'png':y===2026?'webp':'jpg';return `images/acl/acl-${y}-lineup.${ext}`}
years.forEach((y,i)=>{const b=document.createElement('button');b.className='poster-card';b.dataset.index=i;b.setAttribute('aria-label',y===2020?'Show 2020 cancellation details':`Show ${y} lineup; click again to open the full poster`);b.title=y===2020?'2020 festival cancellation':`${y}: center this poster, then click to view it full size`;b.innerHTML=y===2020?'<span class="cancel">2020<br><small>Canceled</small></span>':`<img src="${asset(y)}" alt="ACL Festival ${y} lineup poster" loading="lazy">`;track.append(b)});
const openHint=document.createElement('p');openHint.className='poster-open-hint';openHint.textContent='Click the centered poster to view it full size';openHint.style.cssText='margin:0;text-align:center;color:#a7bbb4;font:500 .58rem var(--mono);letter-spacing:.08em;text-transform:uppercase';caption.after(openHint);const dots=document.createElement('div');dots.className='poster-dots';dots.setAttribute('aria-label','Choose a festival year');years.forEach((y,i)=>{const d=document.createElement('button');d.setAttribute('aria-label',`Show ${y}`);d.addEventListener('click',()=>select(i));dots.append(d)});openHint.after(dots);
const fan=[{x:-510,y:55,r:-18,s:.76,z:1},{x:-365,y:30,r:-12,s:.84,z:2},{x:-200,y:12,r:-6,s:.93,z:3},{x:0,y:0,r:0,s:1,z:10},{x:200,y:12,r:6,s:.93,z:3},{x:365,y:30,r:12,s:.84,z:2},{x:510,y:55,r:18,s:.76,z:1}];
function circularDistance(i,c){let d=i-c;if(d>years.length/2)d-=years.length;if(d<-years.length/2)d+=years.length;return d}function fanMultiplier(){return innerWidth<560?.48:innerWidth<900?.68:1}
function select(i){selected=(i+years.length)%years.length;const mult=fanMultiplier();document.querySelectorAll('.poster-card').forEach((card,n)=>{const d=circularDistance(n,selected),visible=Math.abs(d)<=3;card.classList.toggle('visible',visible);card.classList.toggle('selected',d===0);if(visible){const p=fan[d+3];card.style.setProperty('--x',`${p.x*mult}px`);card.style.setProperty('--y',`${p.y}px`);card.style.setProperty('--r',`${p.r}deg`);card.style.setProperty('--s',p.s);card.style.zIndex=p.z}else card.style.zIndex=0});dots.querySelectorAll('button').forEach((d,n)=>d.classList.toggle('active',n===selected));const y=years[selected],n=notes[y],risingLabel=y===2026?'Rising acts to watch':'Breakout names in hindsight';caption.textContent=y===2020?'2020 · Festival canceled':`${y} lineup`;if(y===2020){details.innerHTML='<h3>2020</h3><div><small>No festival</small><p>ACL Festival was canceled during the COVID-19 pandemic. There was no lineup or gathering in Zilker Park.</p></div>';return}details.innerHTML=`<h3>${y}</h3><div><small>Major acts</small><p>${n?.[0]||'Lineup details coming soon.'}</p></div><div><small>${risingLabel}</small><p>${n?.[1]||'More artist notes coming soon.'}</p></div>${y===2013?'<div class="milestone">Historic first: 2013 was the first ACL Festival held across two weekends. Heavy rain canceled the second Sunday.</div>':''}`}
document.querySelector('#prev').addEventListener('click',()=>select(selected-1));document.querySelector('#next').addEventListener('click',()=>select(selected+1));let wheelLock=false;track.addEventListener('wheel',e=>{e.preventDefault();if(wheelLock)return;wheelLock=true;select(selected+(e.deltaX+e.deltaY>0?1:-1));setTimeout(()=>wheelLock=false,280)},{passive:false});let startX=0,dragged=false;track.addEventListener('pointerdown',e=>{startX=e.clientX;dragged=false;track.classList.add('dragging');track.setPointerCapture(e.pointerId)});track.addEventListener('pointermove',e=>{if(Math.abs(e.clientX-startX)>8)dragged=true});track.addEventListener('pointerup',e=>{const dx=e.clientX-startX;track.classList.remove('dragging');if(Math.abs(dx)>35)select(selected+(dx<0?1:-1))});track.addEventListener('click',e=>{e.preventDefault();if(dragged){dragged=false;return}const visible=[...track.querySelectorAll('.poster-card.visible')],target=visible.reduce((closest,card)=>{const r=card.getBoundingClientRect(),distance=Math.abs(e.clientX-(r.left+r.width/2));return !closest||distance<closest.distance?{card,distance}:closest},null)?.card;if(!target)return;const index=Number(target.dataset.index),year=years[index];if(index===selected&&asset(year))window.open(asset(year),'_blank','noopener');else select(index)});window.addEventListener('resize',()=>select(selected));document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')select(selected-1);if(e.key==='ArrowRight')select(selected+1)});select(selected);
